services:
  db:
    image: postgres:16.4
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: ./.env
    environment:
      - POSTGRES_DB=kawaydb
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=admin
    ports:
      - 5433:5432

  server:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/usr/src/app
    env_file: ./.env
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - PORT=$PORT
      - DATABASE=$DATABASE
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
    ports:
      - 6868:8080

volumes:
  db-data:
    external: true
    name: db_data

